# sample netlify.toml
[build]
command = "nx build --prod"
functions = "functions"
publish = "dist/apps/xmas-commodities"

[dev]
command = "nx serve"
targetPort = 4200
port = 4300
publish = "dist"
autoLaunch = true
framework = "#custom"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
