# sample netlify.toml
[build]
command = "nx build --prod"
functions = "functions"
publish = "dist"

[dev]
command = "nx serve"
targetPort = 4200
port = 4300
publish = "dist"
autoLaunch = true
framework = "#custom"
